#include <graphics.h>
#include <conio.h>

void drawBresenhamLine(int x1, int y1, int x2, int y2)
{
    int m_new = 2 * (y2 - y1);
    int slope_error_new = m_new - (x2 - x1);
    for (int x = x1, y = y1; x <= x2; x++)
    {
        putpixel(x, y, WHITE);
        slope_error_new += m_new;
        if (slope_error_new >= 0)
        {
            y++;
            slope_error_new -= 2 * (x2 - x1);
        }
    }
}

int main()
{
    int gd = DETECT, gm;
    initgraph(&gd, &gm, "C:\\TURBOC3\\BGI");

    // Call drawBresenhamLine with appropriate arguments
    drawBresenhamLine(100, 100, 400, 400);

    getch();
    closegraph();
    return 0;
}